# Generated by Django 3.2.4 on 2021-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_goal_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='difficulty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal_for_month',
            name='goal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goal_for_month',
            name='reason_for_goal',
            field=models.CharField(max_length=50),
        ),
    ]
